import { SESSION_STATUS, SESSION_MODALITY, SESSION_TRACK, SESSION_EVENT_TYPE } from '../types/session';

/**
 * Datos simulados de sesiones para el XI Congreso CONIITI (Oct 1–3, 2026).
 * Incluye casos de borde: cambios de salón, enlaces no verificados, retrasos.
 *
 * @type {import('../types/session').Session[]}
 * @type {import('../types/session').Speaker[]} 
 */

const now = new Date().toISOString();
const recentChange = new Date(Date.now() - 15 * 60 * 1000).toISOString(); // 15 min atrás
const oldChange = new Date(Date.now() - 120 * 60 * 1000).toISOString(); // 2 horas atrás

export const MOCK_SESSIONS = [
    // ─── DÍA 1: Octubre 1 ───
    {
        id: 's1-001',
        titulo: 'Keynote: El Futuro de la IA Generativa en Latinoamérica',
        ponente: 'Dr. Carlos Mendoza',
        speaker_id: 'sp-001',
        event_type: SESSION_EVENT_TYPE.CONFERENCE,
        afiliacion: 'Universidad Nacional de Colombia',
        track: SESSION_TRACK.IA,
        dia: '2026-10-01',
        hora_inicio: '09:00',
        hora_fin: '10:00',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/123456789',
        timestamp_actualizacion: oldChange,
        descripcion: 'Conferencia magistral sobre el impacto de la IA generativa en la transformación digital de América Latina.',
        cupos_totales: 300,
        inscritos: 287,
    },
    {
        id: 's1-002',
        titulo: 'Taller: Desarrollo de APIs Seguras con FastAPI',
        ponente: 'Ing. Laura Prieto',
        speaker_id: 'sp-002',
        event_type: SESSION_EVENT_TYPE.CONFERENCE,
        afiliacion: 'Universidad Católica de Colombia',
        track: SESSION_TRACK.DESARROLLO,
        dia: '2026-10-01',
        hora_inicio: '10:30',
        hora_fin: '12:00',
        salon: 'Sala B2',
        salon_anterior: 'Sala A1',
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.CAMBIO_SALON,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: recentChange,
        descripcion: 'Taller práctico de construcción de APIs RESTful con FastAPI, autenticación JWT y documentación automática.',
        cupos_totales: 40,
        inscritos: 38,
    },
    {
        id: 's1-003',
        titulo: 'Machine Learning para Detección de Amenazas',
        ponente: 'Dr. Andrés Gutiérrez',
        speaker_id: 'sp-003',
        event_type: SESSION_EVENT_TYPE.CONFERENCE,
        afiliacion: 'Universidad de los Andes',
        track: SESSION_TRACK.CIBERSEGURIDAD,
        dia: '2026-10-01',
        hora_inicio: '10:30',
        hora_fin: '11:30',
        salon: 'Sala C3',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.VIRTUAL,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: false,
        link_virtual: 'https://teams.microsoft.com/l/meetup/abc',
        timestamp_actualizacion: now,
        descripcion: 'Uso de modelos de aprendizaje automático para identificar patrones de ataques cibernéticos en tiempo real.',
        cupos_totales: 80,
        inscritos: 45,
    },
    {
        id: 's1-004',
        titulo: 'IoT Industrial: Casos de Éxito en Colombia',
        ponente: 'Ing. María Fernanda López',
        speaker_id: 'sp-004',
        event_type: SESSION_EVENT_TYPE.CONFERENCE,
        afiliacion: 'Siemens Colombia',
        track: SESSION_TRACK.IOT,
        dia: '2026-10-01',
        hora_inicio: '14:00',
        hora_fin: '15:00',
        salon: 'Sala A1',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.RETRASADO,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: recentChange,
        descripcion: 'Implementaciones exitosas de IoT industrial en plantas de manufactura y logística en Colombia.',
        cupos_totales: 60,
        inscritos: 21,
    },

    // ─── DÍA 2: Octubre 2 ───
    {
        id: 's2-001',
        titulo: 'Keynote: Ética y Regulación de Datos en la Era Digital',
        ponente: 'Dra. Sofía Castellanos',
        speaker_id: 'sp-005',
        event_type: SESSION_EVENT_TYPE.WORKSHOP,
        afiliacion: 'MinTIC Colombia',
        track: SESSION_TRACK.DATOS,
        dia: '2026-10-02',
        hora_inicio: '09:00',
        hora_fin: '10:00',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/987654321',
        timestamp_actualizacion: oldChange,
        descripcion: 'Marco regulatorio colombiano para protección de datos personales y gobernanza de IA.',
        cupos_totales: 250,
        inscritos: 198,
    },
    {
        id: 's2-002',
        titulo: 'React Avanzado: Arquitecturas Escalables para SPA',
        ponente: 'Ing. Santiago Rivera',
        speaker_id: 'sp-006',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'Globant',
        track: SESSION_TRACK.DESARROLLO,
        dia: '2026-10-02',
        hora_inicio: '10:30',
        hora_fin: '12:00',
        salon: 'Sala D4',
        salon_anterior: 'Sala B2',
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.CAMBIO_SALON,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: recentChange,
        descripcion: 'Patrones avanzados de React: Compound Components, Context optimization, y Server Components.',
        cupos_totales: 50,
        inscritos: 50,
    },
    {
        id: 's2-003',
        titulo: 'Redes Neuronales para Procesamiento de Lenguaje Natural',
        ponente: 'Dra. Valentina Rojas',
        speaker_id: 'sp-007',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'Universidad Javeriana',
        track: SESSION_TRACK.IA,
        dia: '2026-10-02',
        hora_inicio: '10:30',
        hora_fin: '11:30',
        salon: 'Sala C3',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.VIRTUAL,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://meet.google.com/abc-defg-hij',
        timestamp_actualizacion: oldChange,
        descripcion: 'Aplicaciones de NLP con transformers para análisis de sentimiento en español.',
        cupos_totales: 90,
        inscritos: 67,
    },
    {
        id: 's2-004',
        titulo: 'Blockchain y Ciberseguridad: Nuevos Paradigmas',
        ponente: 'Ing. Ricardo Peña',
        speaker_id: 'sp-008',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'IBM Research',
        track: SESSION_TRACK.CIBERSEGURIDAD,
        dia: '2026-10-02',
        hora_inicio: '14:00',
        hora_fin: '15:00',
        salon: 'Sala A1',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/111222333',
        timestamp_actualizacion: oldChange,
        descripcion: 'Cómo la tecnología blockchain puede fortalecer la seguridad de la infraestructura digital.',
        cupos_totales: 120,
        inscritos: 88,
    },

    // ─── DÍA 3: Octubre 3 ───
    {
        id: 's3-001',
        titulo: 'Tendencias 2026: Computación Cuántica y su Impacto',
        ponente: 'Dr. Felipe Martínez',
        speaker_id: 'sp-009',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'Google DeepMind',
        track: SESSION_TRACK.INNOVACION,
        dia: '2026-10-03',
        hora_inicio: '09:00',
        hora_fin: '10:00',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/444555666',
        timestamp_actualizacion: oldChange,
        descripcion: 'Estado actual y perspectivas de la computación cuántica para la industria tecnológica.',
        cupos_totales: 300,
        inscritos: 241,
    },
    {
        id: 's3-002',
        titulo: 'Edge Computing y Smart Cities',
        ponente: 'Ing. Natalia Herrera',
        speaker_id: 'sp-010',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'Cisco Systems',
        track: SESSION_TRACK.IOT,
        dia: '2026-10-03',
        hora_inicio: '10:30',
        hora_fin: '11:30',
        salon: 'Sala B2',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: oldChange,
        descripcion: 'Arquitecturas de edge computing para ciudades inteligentes y movilidad urbana.',
        cupos_totales: 70,
        inscritos: 33,
    },
    {
        id: 's3-003',
        titulo: 'Data Governance: Del Caos al Orden en la Nube',
        ponente: 'Dra. Camila Ortiz',
        speaker_id: 'sp-011',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'AWS Colombia',
        track: SESSION_TRACK.DATOS,
        dia: '2026-10-03',
        hora_inicio: '10:30',
        hora_fin: '12:00',
        salon: 'Sala A1',
        salon_anterior: 'Sala C3',
        modalidad: SESSION_MODALITY.VIRTUAL,
        status_logistico: SESSION_STATUS.CAMBIO_SALON,
        link_verificado: false,
        link_virtual: 'https://chime.aws/meeting/xyz',
        timestamp_actualizacion: recentChange,
        descripcion: 'Estrategias de gobernanza de datos en entornos multi-cloud con herramientas de AWS.',
        cupos_totales: 100,
        inscritos: 99,
    },
    {
        id: 's3-004',
        titulo: 'Panel de Cierre: Innovación Abierta en Ingeniería',
        ponente: 'Panel Multidisciplinario',
        speaker_id: 'sp-012',
        event_type: SESSION_EVENT_TYPE.SYMPOSIUM,
        afiliacion: 'CONIITI',
        track: SESSION_TRACK.INNOVACION,
        dia: '2026-10-03',
        hora_inicio: '15:00',
        hora_fin: '16:30',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/777888999',
        timestamp_actualizacion: oldChange,
        descripcion: 'Panel de cierre con representantes de academia, industria y gobierno discutiendo el futuro de la innovación.',
        cupos_totales: 300,
        inscritos: 156,
    },
];

/** Días de conferencia disponibles para la interfaz de filtro */
export const CONFERENCE_DAYS = [
    { value: '2026-10-01', label: 'Oct 1' },
    { value: '2026-10-02', label: 'Oct 2' },
    { value: '2026-10-03', label: 'Oct 3' },
];


export const MOCK_SPEAKERS = [
    {
        id: 'sp-001',
        name: 'Dr. Carlos Mendoza',
        role: 'Directos de Innovación',
        affiliation: 'Universidad Nacional de Colombia',
        bio: 'Experto en IA generativa con más de 15 años de trayectoría en investigación de modelos de lenguaje hnasdofao fneaou rfhneqwui hrfuoeqwh fuioweh fouewhf puowehfuio hewuorf hwepuof hweufh weuofh weu9fh eu9wqhf puioeqwhf pueqwh fu9heqwu9f hweu9hf 9weuqh fu9ewh f9uqweh fuhwequ9 hfu9weq hfu9weh u9fhewu9 fhweu9 hfu9wehf u9ewhf u9weqhf u9hwequ9f hnqweu9fh opúiewfhn ipuowefb i9pewafhn poiáewhnfpuawerhg 9opierwahg9puerawhg 9awejg 9uhwiog hwqrug hweiqg hu9weqjhg 9uweqhg 0iweaqhjg u9wehg io.',
        photo_url: 'https://labsaenzrenauld.com/wp-content/uploads/2020/10/Perfil-hombre-ba%CC%81sico_738242395.jpg',
        country: 'Colombia'
    },
    {
        id: 'sp-002',
        name: 'Ing. Laura Prieto',
        role: 'Arquitecta de Software Senior',
        affiliation: 'Especialista en arquitecturas distribuidas y seguridad en la nube',
        photo_url: 'https://www.seoptimer.com/storage/images/2016/05/foto-de-perfil-adecuada.jpg',
        country: 'España'
    }
];