import { SESSION_STATUS, SESSION_MODALITY, SESSION_TRACK } from '../types/session';

/**
 * Datos simulados de sesiones para el XI Congreso CONIITI (Oct 1–3, 2025).
 * Incluye casos de borde: cambios de salón, enlaces no verificados, retrasos.
 *
 * @type {import('../types/session').Session[]}
 */

const now = new Date().toISOString();
const recentChange = new Date(Date.now() - 15 * 60 * 1000).toISOString(); // 15 min atrás
const oldChange = new Date(Date.now() - 120 * 60 * 1000).toISOString(); // 2 horas atrás

export const MOCK_SESSIONS = [
    // ─── DÍA 1: Octubre 1 ───
    {
        id: 's1-001',
        titulo: 'Keynote: El Futuro de la IA Generativa en Latinoamérica',
        ponente: 'Dr. Carlos Mendoza',
        afiliacion: 'Universidad Nacional de Colombia',
        track: SESSION_TRACK.IA,
        dia: '2025-10-01',
        hora_inicio: '09:00',
        hora_fin: '10:00',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/123456789',
        timestamp_actualizacion: oldChange,
        descripcion: 'Conferencia magistral sobre el impacto de la IA generativa en la transformación digital de América Latina.',
    },
    {
        id: 's1-002',
        titulo: 'Taller: Desarrollo de APIs Seguras con FastAPI',
        ponente: 'Ing. Laura Prieto',
        afiliacion: 'Universidad Católica de Colombia',
        track: SESSION_TRACK.DESARROLLO,
        dia: '2025-10-01',
        hora_inicio: '10:30',
        hora_fin: '12:00',
        salon: 'Sala B2',
        salon_anterior: 'Sala A1',
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.CAMBIO_SALON,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: recentChange,
        descripcion: 'Taller práctico de construcción de APIs RESTful con FastAPI, autenticación JWT y documentación automática.',
    },
    {
        id: 's1-003',
        titulo: 'Machine Learning para Detección de Amenazas',
        ponente: 'Dr. Andrés Gutiérrez',
        afiliacion: 'Universidad de los Andes',
        track: SESSION_TRACK.CIBERSEGURIDAD,
        dia: '2025-10-01',
        hora_inicio: '10:30',
        hora_fin: '11:30',
        salon: 'Sala C3',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.VIRTUAL,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: false,
        link_virtual: 'https://teams.microsoft.com/l/meetup/abc',
        timestamp_actualizacion: now,
        descripcion: 'Uso de modelos de aprendizaje automático para identificar patrones de ataques cibernéticos en tiempo real.',
    },
    {
        id: 's1-004',
        titulo: 'IoT Industrial: Casos de Éxito en Colombia',
        ponente: 'Ing. María Fernanda López',
        afiliacion: 'Siemens Colombia',
        track: SESSION_TRACK.IOT,
        dia: '2025-10-01',
        hora_inicio: '14:00',
        hora_fin: '15:00',
        salon: 'Sala A1',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.RETRASADO,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: recentChange,
        descripcion: 'Implementaciones exitosas de IoT industrial en plantas de manufactura y logística en Colombia.',
    },

    // ─── DÍA 2: Octubre 2 ───
    {
        id: 's2-001',
        titulo: 'Keynote: Ética y Regulación de Datos en la Era Digital',
        ponente: 'Dra. Sofía Castellanos',
        afiliacion: 'MinTIC Colombia',
        track: SESSION_TRACK.DATOS,
        dia: '2025-10-02',
        hora_inicio: '09:00',
        hora_fin: '10:00',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/987654321',
        timestamp_actualizacion: oldChange,
        descripcion: 'Marco regulatorio colombiano para protección de datos personales y gobernanza de IA.',
    },
    {
        id: 's2-002',
        titulo: 'React Avanzado: Arquitecturas Escalables para SPA',
        ponente: 'Ing. Santiago Rivera',
        afiliacion: 'Globant',
        track: SESSION_TRACK.DESARROLLO,
        dia: '2025-10-02',
        hora_inicio: '10:30',
        hora_fin: '12:00',
        salon: 'Sala D4',
        salon_anterior: 'Sala B2',
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.CAMBIO_SALON,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: recentChange,
        descripcion: 'Patrones avanzados de React: Compound Components, Context optimization, y Server Components.',
    },
    {
        id: 's2-003',
        titulo: 'Redes Neuronales para Procesamiento de Lenguaje Natural',
        ponente: 'Dra. Valentina Rojas',
        afiliacion: 'Universidad Javeriana',
        track: SESSION_TRACK.IA,
        dia: '2025-10-02',
        hora_inicio: '10:30',
        hora_fin: '11:30',
        salon: 'Sala C3',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.VIRTUAL,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://meet.google.com/abc-defg-hij',
        timestamp_actualizacion: oldChange,
        descripcion: 'Aplicaciones de NLP con transformers para análisis de sentimiento en español.',
    },
    {
        id: 's2-004',
        titulo: 'Blockchain y Ciberseguridad: Nuevos Paradigmas',
        ponente: 'Ing. Ricardo Peña',
        afiliacion: 'IBM Research',
        track: SESSION_TRACK.CIBERSEGURIDAD,
        dia: '2025-10-02',
        hora_inicio: '14:00',
        hora_fin: '15:00',
        salon: 'Sala A1',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/111222333',
        timestamp_actualizacion: oldChange,
        descripcion: 'Cómo la tecnología blockchain puede fortalecer la seguridad de la infraestructura digital.',
    },

    // ─── DÍA 3: Octubre 3 ───
    {
        id: 's3-001',
        titulo: 'Tendencias 2026: Computación Cuántica y su Impacto',
        ponente: 'Dr. Felipe Martínez',
        afiliacion: 'Google DeepMind',
        track: SESSION_TRACK.INNOVACION,
        dia: '2025-10-03',
        hora_inicio: '09:00',
        hora_fin: '10:00',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/444555666',
        timestamp_actualizacion: oldChange,
        descripcion: 'Estado actual y perspectivas de la computación cuántica para la industria tecnológica.',
    },
    {
        id: 's3-002',
        titulo: 'Edge Computing y Smart Cities',
        ponente: 'Ing. Natalia Herrera',
        afiliacion: 'Cisco Systems',
        track: SESSION_TRACK.IOT,
        dia: '2025-10-03',
        hora_inicio: '10:30',
        hora_fin: '11:30',
        salon: 'Sala B2',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.PRESENCIAL,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: false,
        link_virtual: null,
        timestamp_actualizacion: oldChange,
        descripcion: 'Arquitecturas de edge computing para ciudades inteligentes y movilidad urbana.',
    },
    {
        id: 's3-003',
        titulo: 'Data Governance: Del Caos al Orden en la Nube',
        ponente: 'Dra. Camila Ortiz',
        afiliacion: 'AWS Colombia',
        track: SESSION_TRACK.DATOS,
        dia: '2025-10-03',
        hora_inicio: '10:30',
        hora_fin: '12:00',
        salon: 'Sala A1',
        salon_anterior: 'Sala C3',
        modalidad: SESSION_MODALITY.VIRTUAL,
        status_logistico: SESSION_STATUS.CAMBIO_SALON,
        link_verificado: false,
        link_virtual: 'https://chime.aws/meeting/xyz',
        timestamp_actualizacion: recentChange,
        descripcion: 'Estrategias de gobernanza de datos en entornos multi-cloud con herramientas de AWS.',
    },
    {
        id: 's3-004',
        titulo: 'Panel de Cierre: Innovación Abierta en Ingeniería',
        ponente: 'Panel Multidisciplinario',
        afiliacion: 'CONIITI',
        track: SESSION_TRACK.INNOVACION,
        dia: '2025-10-03',
        hora_inicio: '15:00',
        hora_fin: '16:30',
        salon: 'Auditorio Principal',
        salon_anterior: null,
        modalidad: SESSION_MODALITY.HIBRIDO,
        status_logistico: SESSION_STATUS.NORMAL,
        link_verificado: true,
        link_virtual: 'https://zoom.us/j/777888999',
        timestamp_actualizacion: oldChange,
        descripcion: 'Panel de cierre con representantes de academia, industria y gobierno discutiendo el futuro de la innovación.',
    },
];

/** Días de conferencia disponibles para la interfaz de filtro */
export const CONFERENCE_DAYS = [
    { value: '2025-10-01', label: 'Oct 1' },
    { value: '2025-10-02', label: 'Oct 2' },
    { value: '2025-10-03', label: 'Oct 3' },
];
