http:
  routers:
    auth:
      rule: "PathPrefix(`/api/auth`)"
      entryPoints:
        - web
      middlewares:
        - strip-auth
      service: auth-svc

    payments:
      rule: "PathPrefix(`/api/payments`)"
      entryPoints:
        - web
      service: payments-svc

    files:
      rule: "PathPrefix(`/api/files`)"
      entryPoints:
        - web
      service: files-svc

    analytics:
      rule: "PathPrefix(`/api/analytics`)"
      entryPoints:
        - web
      service: analytics-svc

  middlewares:
    strip-auth:
      stripPrefix:
        prefixes:
          - /api/auth

  services:
    auth-svc:
      loadBalancer:
        servers:
          - url: "http://auth-service:8000"

    payments-svc:
      loadBalancer:
        servers:
          - url: "http://payments-service:8000"

    files-svc:
      loadBalancer:
        servers:
          - url: "http://files-service:8000"

    analytics-svc:
      loadBalancer:
        servers:
          - url: "http://analytics-service:8000"
