"""Add descripcion_ponente to sessions

Revision ID: 0d5bcc3a4a7f
Revises: 1eead8763bb6
Create Date: 2026-03-08 00:28:19.252038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5bcc3a4a7f'
down_revision: Union[str, None] = '1eead8763bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('descripcion_ponente', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'descripcion_ponente')
    # ### end Alembic commands ###
