"""add_password_reset_to_otppurpose

Revision ID: 1eead8763bb6
Revises: fef5106ac0d0
Create Date: 2026-03-07 23:39:12.360929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eead8763bb6'
down_revision: Union[str, None] = 'fef5106ac0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
