"""add_speaker_fields_and_documents_table

Revision ID: 586e3b79f9ba
Revises: 6b21b4b23bcd
Create Date: 2026-04-03 18:34:50.473813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586e3b79f9ba'
down_revision: Union[str, None] = '6b21b4b23bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coniiti_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('ponente_nombre', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coniiti_documents_id'), 'coniiti_documents', ['id'], unique=False)
    op.add_column('sessions', sa.Column('foto_ponente_url', sa.String(length=1000), nullable=True))
    op.add_column('sessions', sa.Column('es_conferencista_principal', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'es_conferencista_principal')
    op.drop_column('sessions', 'foto_ponente_url')
    op.drop_index(op.f('ix_coniiti_documents_id'), table_name='coniiti_documents')
    op.drop_table('coniiti_documents')
    # ### end Alembic commands ###
