"""Add subtitle and year

Revision ID: 6b21b4b23bcd
Revises: 794e23f275b6
Create Date: 2026-03-09 18:35:30.654438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b21b4b23bcd'
down_revision: Union[str, None] = '794e23f275b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_cards', sa.Column('subtitle', sa.String(length=255), nullable=True))
    op.add_column('content_cards', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_cards', 'year')
    op.drop_column('content_cards', 'subtitle')
    # ### end Alembic commands ###
