"""CMS ContentCard

Revision ID: 7594965fe641
Revises: 0d5bcc3a4a7f
Create Date: 2026-03-08 09:21:22.311088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7594965fe641'
down_revision: Union[str, None] = '0d5bcc3a4a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('link_url', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_cards_id'), 'content_cards', ['id'], unique=False)
    op.create_index(op.f('ix_content_cards_section'), 'content_cards', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_cards_section'), table_name='content_cards')
    op.drop_index(op.f('ix_content_cards_id'), table_name='content_cards')
    op.drop_table('content_cards')
    # ### end Alembic commands ###
