"""initial

Revision ID: fef5106ac0d0
Revises: 
Create Date: 2026-03-07 22:30:30.686499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef5106ac0d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPERUSER', 'STAFF', 'STUDENT', 'EXTERNAL', name='userrole'), nullable=False),
    sa.Column('auth_provider', sa.Enum('LOCAL', 'MICROSOFT', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('accepted_data_policy', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTER', 'LOGIN', name='otppurpose'), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ponente', sa.String(length=255), nullable=False),
    sa.Column('afiliacion', sa.String(length=255), nullable=True),
    sa.Column('speaker_id', sa.String(length=50), nullable=True),
    sa.Column('track', sa.Enum('IA', 'CIBERSEGURIDAD', 'IOT', 'DESARROLLO', 'DATOS', 'INNOVACION', name='sessiontrack'), nullable=False),
    sa.Column('event_type', sa.Enum('CONFERENCE', 'WORKSHOP', 'SYMPOSIUM', 'PANEL', name='sessioneventtype'), nullable=False),
    sa.Column('dia', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.Column('salon', sa.String(length=255), nullable=False),
    sa.Column('salon_anterior', sa.String(length=255), nullable=True),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'VIRTUAL', 'HIBRIDO', name='sessionmodality'), nullable=False),
    sa.Column('status_logistico', sa.Enum('NORMAL', 'CAMBIO_SALON', 'RETRASADO', name='sessionstatus'), nullable=False),
    sa.Column('link_virtual', sa.String(length=1000), nullable=True),
    sa.Column('link_verificado', sa.Boolean(), nullable=False),
    sa.Column('cupos_totales', sa.Integer(), nullable=False),
    sa.Column('inscritos', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('timestamp_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_dia'), 'sessions', ['dia'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_titulo'), 'sessions', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_titulo'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_dia'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
