name: CI/CD CONIITI - Control de Calidad

# ---
on:
  push:
    branches:
      - desarrollo-rediseno
  pull_request:
    branches:
      - desarrollo-rediseno
      - main

jobs:
  verificacion:
    name: Revisión Automática
    runs-on: ubuntu-latest

    # le indica a GitHub que todo esto debe correr en la carpeta Frontend
    defaults:
      run:
        working-directory: ./Front-end

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm ci

      - name: Paso 1 - Ejecutar Linting
        run: npm run lint

      - name: Paso 2 - Pruebas Unitarias
        run: npm run test

      - name: Paso 3 - Build Estricto
        run: npm run build:strict
